---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 12952.
--- DateTime: 2025/3/20 15:58
---
local voucher_id = ARGV[1]
local user_id = ARGV[2]

-- 数据key
local stock_key = 'seckill:stock:' .. voucher_id
local order_key = 'seckill:order:' .. voucher_id

-- 脚本业务
-- 判断库存是否充足
if(tonumber(redis.call("get", stock_key))<=0) then
    return 1
end
-- 判断用户是否重复购买
if(redis.call("sismember", order_key, user_id) == 1) then
    return 2
end

redis.call("incrby", stock_key, -1)
redis.call("sadd", order_key, user_id)
return 0
